enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: AFT Unit
  - name: Sandbox
  - name: Suspended
    ignore: true
serviceControlPolicies: []
taggingPolicies: []
chatbotPolicies: []
backupPolicies: []
